In [2]:
"""ライブラリ読み込み"""
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np

In [3]:
"""GPU設定"""
# GPUが利用できる場合はGPUを利用し，利用不可の場合はCPUを利用
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [4]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [5]:
# データロード
iris = datasets.load_iris()

# 説明変数 "Sepal Length", "Sepal Width", "Petal Length", "Petal Width"
x = iris.data.astype(np.float32)
# 目的変数 "Specoes"
y = iris.target.astype(np.int64)

In [6]:
print(f'x = {x}')
print(f'y = {y}')

x = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.

In [7]:
# 学習データ & テストデータ分割
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=3)

# テンソル化
x_train, x_test, y_train, y_test = torch.from_numpy(x_train).to(device), torch.from_numpy(x_test).to(device), torch.from_numpy(y_train).to(device), torch.from_numpy(y_test).to(device)

In [8]:
x_train

tensor([[6.4000, 3.2000, 4.5000, 1.5000],
        [5.1000, 3.3000, 1.7000, 0.5000],
        [6.0000, 2.7000, 5.1000, 1.6000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [5.4000, 3.0000, 4.5000, 1.5000],
        [4.8000, 3.0000, 1.4000, 0.3000],
        [5.0000, 3.2000, 1.2000, 0.2000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [6.1000, 2.8000, 4.7000, 1.2000],
        [4.9000, 3.1000, 1.5000, 0.2000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [5.1000, 3.8000, 1.5000, 0.3000],
        [6.5000, 3.0000, 5.5000, 1.8000],
        [5.7000, 2.9000, 4.2000, 1.3000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [6.8000, 3.2000, 5.9000, 2.3000],
        [5.9000, 3.2000, 4.8000, 1.8000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [5.1000, 2.5000, 3.0000, 1.1000],
        [6.4000, 3.1000, 5.5000, 1.8000],
        [6.3000, 3.3000, 6.0000, 2

In [9]:
# 学習データの説明変数
print(x_train.shape)

torch.Size([105, 4])


In [10]:
# 学習データの目的変数
print(y_train.shape)

torch.Size([105])


In [11]:
"""(2)モデルクラスの登録"""
# nnクラスの関数(初期設定)を下記に記述
class IrisModel(nn.Module):

    def __init__(self):
        super(IrisModel, self).__init__()

        # モジュールリストの中にモデル情報を記述
        self.model_info = nn.ModuleList([
            nn.Linear(4,6), # (1)入力層:今回入力は4次元として設定・出力は6次元と任意に設定
            nn.Sigmoid(),   # (2)活性化関数(シグモイド)
            nn.Linear(6,3), # (3)出力層:出力層のユニットは出力値分
        ])
        
    # 純方向伝播の計算を記述
    def forward(self, x):
        for i in range(len(self.model_info)):
            x = self.model_info[i](x)
        return x

In [12]:
"""(3)モデルとパラメータ探索アルゴリズムの設定"""
model = IrisModel().to(device) # モデル
optimizer = optim.SGD(model.parameters(),lr=0.05) # パラメータ探索アルゴリズム(確率的勾配降下法 + 額収率lr=0.05を適用)
criterion = nn.CrossEntropyLoss() # 損失関数

In [13]:
"""代表的な損失関数には下記のようなものがある"""
# 二値分類 | バイナリ交差エントロピー損失
criterion = nn.BCELoss

# 二値分類 | ロジット付きバイナリ交差エントロピー損失
criterion = nn.BCELoss

# 多クラス分類 | Softmax交差エントロピー損失
criterion = nn.CrossEntropyLoss()

# 回帰 | 平均二乗誤差
criterion = nn.MSELoss

# 回帰 | 平均絶対値誤差
criterion = nn.L1Loss

In [14]:
criterion = nn.CrossEntropyLoss()

In [15]:
"""(4)モデル学習 バッチ学習を適用"""
# 学習回数
repeat = 1500

for epoch in range(repeat):
    ex_var = x_train # 説明変数を作成
    target = y_train # 目的変数を作成

    # モデルのforward関数を用いた順伝播の予測(モデルの出力地算出)
    output = model(ex_var)
    
    # 上記出力値(output)と教師データ(target)を損失関数に渡し，損失関数を計算
    loss = criterion(output, target)

    # 勾配を初期化
    optimizer.zero_grad()

    # 損失関数の値から勾配を求め，誤差逆伝播による学習実行
    loss.backward()

    # 学習結果に基づきパラメータを更新
    optimizer.step()

<All keys matched successfully>

In [16]:
"""(5)モデルの結果を出力"""
torch.save(model.state_dict(),"sample.model") # モデル保存する場合
model.load_state_dict(torch.load("sample.model")) # モデルを呼び出す場合

<All keys matched successfully>

In [17]:
"""(6)モデルの性能評価"""

# 学習したモデルの評価
model.eval()
with torch.no_grad():
    pred_model = model(x_test) # テストデータモデル推論
    pred_result = torch.argmax(pred_model,1) # 予測値

    # 正解率
    print(round(((y_test == pred_result).sum()/len(pred_result)).item(),3))

0.956


In [18]:
"""(4)モデル学習"""
data_size = len(x_train) # データのサイズ
mini_batch = int(data_size * 3/4) # ミニバッチサイズ(全データの3/4を学習に利用)
repeat = 1500 # エポック数

for epoch in range(repeat):

    # per,utation = 渡した引数の数値をシャッフル
    dx = np.random.permutation(data_size)

    for num in range(0,data_size,mini_batch):

        # 説明変数(ミニバッチサイズ)
        ex_var = x_train[dx[num:(num + mini_batch) if (num + mini_batch) < data_size else data_size]]

        # 目的変数(ミニバッチサイズ)
        target = y_train[dx[num:(num + mini_batch) if (num + mini_batch) < data_size else data_size]]

        # モデルのforward関数を用いた準伝播の予測→出力値算出
        output = model(ex_var)

        # 上記出力値(output)と教師データ(target)を損失関数に渡し，損失関数を計算
        loss = criterion(output, target)

        # 勾配を初期化
        optimizer.zero_grad()

        #  損失関数の値から勾配を求めた誤差逆伝播による学習実行
        loss.backward()

        # 学習結果に基づきパラメータを更新
        optimizer.step()

In [19]:
"""(5)モデルの結果を出力"""
torch.save(model.state_dict(),"sample.model") # モデル保存する場合
model.load_state_dict(torch.load("sample.model")) # モデルを呼び出す場合

<All keys matched successfully>

In [20]:
"""(6)モデルの性能評価"""

# 学習したモデルの評価
model.eval()
with torch.no_grad():
    pred_model = model(x_test) # テストデータモデル推論
    pred_result = torch.argmax(pred_model,1) # 予測値

    # 正解率
    print(round(((y_test == pred_result).sum()/len(pred_result)).item(),3))

0.956


In [21]:
""" ライブラリ読込 """
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split


""" GPU設定 """
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


""" (1) データの準備 """
# データロード
iris = datasets.load_iris()
# 説明変数 "Sepal Length", "Sepal Width", "Petal Length", "Petal Width"
X = iris.data.astype(np.float32)
# 目的変数 "Species"
Y = iris.target.astype(np.int64)
# 学習データ＆テストデータ分割
X_train, X_test,  Y_train, Y_test = train_test_split(X,Y,test_size=0.3, random_state=3)
# テンソル化
X_train, X_test, Y_train, Y_test = torch.from_numpy(X_train).to(device), torch.from_numpy(X_test).to(device), torch.from_numpy(Y_train).to(device), torch.from_numpy(Y_test).to(device)


""" (2)モデル情報を記述 """
# nnクラスの関数(初期設定)を下記に記述
class IrisModel(nn.Module):
    
    # ユニット・層の数・活性化関数等ニューラルネットワークの模型となるものを下記に記述
    def __init__(self):
        super(IrisModel, self).__init__()
        self.model_info = nn.ModuleList([
             nn.Linear(4,6),   # 入力層
             nn.Sigmoid(),     # 活性化関数(シグモイド)
             nn.Linear(6,3),   # 出力層
            ])
    
    # 順方向の計算処理の流れを下記に記述
    def forward(self,x):
        for i in range(len(self.model_info)):
            x = self.model_info[i](x)
        return x


""" (3)モデルとパラメータ探索アルゴリズムの設定 """
model     = IrisModel().to(device)                # モデル
optimizer = optim.SGD(model.parameters(),lr=0.05) # パラメータ探索アルゴリズム
criterion = nn.CrossEntropyLoss()                 # 損失関数


""" (4) モデル学習 """
data_size  = len(X_train)           # データのサイズ
mini_batch = int(data_size * 3/4)   # ミニバッチサイズ
repeat = 1500                       # エポック数

for epoch in range(repeat):
    
    # permutation(渡した引数の数値をシャッフル)
    dx = np.random.permutation(data_size)
    
    for num in range(0,data_size,mini_batch):
        # 説明変数(ミニバッチサイズ)
        ex_var = X_train[dx[num:(num + mini_batch) if (num + mini_batch) < data_size else data_size]]
        # 目的変数(ミニバッチサイズ)
        target = Y_train[dx[num:(num + mini_batch) if (num + mini_batch) < data_size else data_size]] 
        # モデルのforward関数を用いた準伝播の予測→出力値算出
        output = model(ex_var)  
        # 上記出力値(output)と教師データ(target)を損失関数に渡し、損失関数を計算
        loss = criterion(output, target)
        # 勾配を初期化
        optimizer.zero_grad()
        # 損失関数の値から勾配を求め誤差逆伝播による学習実行
        loss.backward()
        # 学習結果に基づきパラメータを更新
        optimizer.step()


""" (5)モデルの結果を出力 """
# torch.save(model.state_dict(), "iris.model")    # モデル保存する場合
# model.load_state_dict(torch.load("iris.model")) # モデルを呼び出す場合


""" (6) モデルの性能評価 """
model.eval()
with torch.no_grad():
    pred_model  = model(X_test)
    pred_result = torch.argmax(pred_model,1) #予測値
    print("正解率: " + str(round(((Y_test == pred_result).sum()/len(pred_result)).item(),3))+"[%]")

正解率: 0.956[%]
