# Pytorch 学習2

## 自動微分 (Autograd)

In [1]:
import torch

In [3]:
sample1 = torch.ones(2,2,requires_grad=True)
print(sample1)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
graph1 = sample1 + 2
print(graph1)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
graph2 = graph1 * graph1 * 3
consequence = graph2.mean()
print(graph2, consequence)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
consequence.backward()

In [7]:
print(graph1.grad)

None


c:\Users\shora\Anaconda3\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad
